spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hoxify
    username: ismat
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      javax:
        persistence:
          validation:
            mode: none